module.exports = [{
    id: 1,
    date: "06-30-2018",
    artist:"RUMTUM",
    venue: "Hi-Dive",
    contactName: "Rummer Tummer",
    phone:"303-333-3333",
    email:"rumtum@aol.com",
    website:"http://www.wikipedia.com",
    musicSample: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/105119837&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true",
    image: "https://images1.westword.com/imager/moving-to-denver-has-been-highly-fortuitou/u/745xauto/5122142/9195074.0.jpg",
    description: "Denver's headiest beatmaker blurs the lines between dance, organic world music, and old-fashioned dope beats."
},
{
    id: 2,
    date: "06-28-2018",
    artist:"Slipknot",
    venue: "Ogden",
    contactName: "Peter Chun",
    phone:"555-555-5555",
    email:"no@no.com",
    website:"http://www.yahoo.com",
    musicSample:"https://soundcloud.com/nycpride/episode-56-dj-alex-acosta",
    image: "https://images-na.ssl-images-amazon.com/images/I/81lrF8AR%2BtL._SX522_.jpg",
    description: "Murder Inc.",
},
{
    id: 3,
    date: "06-15-2018",
    artist: "Lady Gaga",
    venue: "Filmore",
    contactName:"Jack Black",
    phone:"404-909-8877",
    email:"yes@yes.com",
    website:"http://www.aol.com",
    musicSample:"https://soundcloud.com/interscope/lady-gaga-applause-official",
    image: "https://eonlinethumbs-a.akamaihd.net/images/647/471/glam_2018grammys_ladygaga_268370_560x315_1148015171950.jpg",

    description: "Pop star",
}]